name: build
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '19.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          dart pub outdated
          dart format
          flutter build apk --debug
